credentials:
  usernames:
    labib:
      email: labib@gmail.com
      name: labib
      password: $2b$12$zFVPP5wU8TOjXGFR09PwUusSB8TouEM7Ftw6//pENeV6DEYNQBga6
    tushi:
      email: tushi@gmail.com
      name: tushi
      password: $2b$12$ej0fGmCcgqy4M/A0eld88.uMpcVanaRf5.rlKAz9HQG8y4E/Cf2cm
cookie:
  expiry_days: 30
  key: secret_cookie
  name: mycookie
preauthorized:
  emails:
  - test@gmail.com